Jupyter lab support
daipe-ai/dbx-deploy pull request #10
Opened 2021-05-10 09:00 UTC by chlubnamarek

Percent separators support added
Databricks notebooks deployment updated
Ignoring jupyter notebooks checkpoints folders for deployment

2021-05-10 11:02 UTC, kutny requested changes

2021-05-10 11:02 UTC, kutny commented on src/dbxdeploy/_config/config.yaml
> +#  dbxdeploy.notebook.converter.DatabricksNotebookConverter:
Remove this pls

2021-05-11 14:11 UTC, kutny commented on src/dbxdeploy/_config/config.yaml
> +        cell_separator: 'percent' # command or percent
Just note: I would choose "command" as default value for now as this is still a bit experimental feature and we want to make it backward compatible.

2021-05-12 10:05 UTC, kutny requested changes

2021-05-12 10:05 UTC, kutny commented on src/dbxdeploy/notebook/loader.py
>  def load_notebook(notebook_path: Path) -> str:
Why haven't you changed NotebooksLocator class instead?

2021-05-26 13:46 UTC, guderkar approved these changes
ok

2021-05-26 13:46 UTC, merged